In [3]:
#Kauã Antônio Reis
import numpy as np

In [7]:
#Question 1
np.ones(12).reshape(4,3)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [6]:
#Question 2
matriz = np.random.randn(20)
media = np.mean(matriz)
desvio = np.std(matriz)
soma = np.sum(matriz)
print("Matriz:", matriz)
print("Média:", media)
print("Desvio:", desvio)
print("Soma:", soma)





Matriz: [ 0.18744397 -0.550635    0.67903706  1.9464551  -0.95447034  0.09118007
 -0.18941983 -1.03437288  2.40052414  1.26427127 -1.94090903 -1.27236506
  0.63301896  1.33694159 -1.30313935 -1.70545798  0.78817625 -0.70282183
 -0.82393521 -2.369717  ]
Média: -0.17600975555422554
Desvio: 1.2834541412637985
Soma: -3.5201951110845107


In [42]:
#Question 3
array1 = np.arange(1,6)
array2 = np.arange(6,11) 
soma = array1 + array2
subtração = array1 - array2
multiplicaçao = array1 * array2
print(soma)
print(subtração)
print(multiplicaçao)



[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]


In [ ]:
#Question 4
#O broadcasting no NumPy é um mecanismo que permite realizar operações aritméticas entre arrays de formas e tamanhos diferentes. 
#Quando duas matrizes são usadas em uma operação, 
#o NumPy compara suas formas elemento por elemento, começando pela última dimensão.
a = np.array([[1, 2, 3],
              [4, 5, 6]])
b = np.array([10, 20, 30])

# b é expandido (broadcasted) para cada linha de a
resultado = a + b
resultado2 = a + b[:, None]
print(resultado)
print(resultado2)

[[11 22 33]
 [14 25 36]]


In [ ]:
#Question 5
A = np.array([[10, 20, 30],
              [40, 50, 60],
              [70, 80, 90]])

# a)
third_column = A[:,2]

# b)
bottom_right_element = A[2,2]

# c) 
B = A[1:,0:2]

print(third_column)
print(bottom_right_element)
print(B)


[30 60 90]
90
[[40 50]
 [70 80]]


In [17]:
#Question 6
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[2, 0],
              [1, 3]])

# a)
AB = np.dot(A, B)

# (b) 
BA = np.dot(B, A)

# AB = BA
equal = np.array_equal(AB, BA)

print(AB)
print(equal)

[[ 4  6]
 [10 12]]
False
